### ISSUE TITLE
Auto-complete in JSON file

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#100] opened 2020-11-06 23:42 UTC
Developers may find it tough to remember what is allowed in the JSON file. We received a suggestion for implementing auto-complete in the JSON file. 

Thank you to @hugoabernier for the following suggestion:

"If you add "$schema": "https://raw.githubusercontent.com/vsls-contrib/codetour/master/schema.json", to the top of your .tour file, you’ll get auto-completion (see screenshot, below).

![screenshot](https://user-images.githubusercontent.com/12738587/98424575-0e12e280-2060-11eb-89e7-c435117fd4ec.png)
 
My recommendation would be to take your schema.json file and point it to a static URL (something like https://developer.microsoft.com/json-schemas/vsls-contrib/codetour/schema.json) and change your .tour template file to include the $schema attribute at the top, so that all new tours can automatically provide auto-complete functionality to users."

**Comment by lostintangent** [comment] 2020-11-07 03:00
Closing this as a duplicate of #91.

**Closed by lostintangent** 2020-11-07 03:00 UTC
Labels: area: recording
