### ISSUE TITLE
Improve getting started experience

### ISSUE THREAD

**Issue by alpaix** [vsls-contrib/codetour#71] opened 2020-05-20 01:12 UTC
I'm unable to use the extension due to following issues:
1. CodeTour tree is not available in the explorer pane.
1. I was able to invoke "Record tour" via command palette. But markers are not shown in the editor gutter.

I work in a multi-root workspace containing a variety of TypeScript projects.

VSCode
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by lostintangent** [comment] 2020-05-20 01:42
Hey! Currently, the CodeTour tree only appears if the opened workspace has one or more tours associated with it. That decision was made to prevent the CodeTour tree from cluttering the VS Code UI, when working on projects that don’t have any tours. Did you open a project that has tours, but yet you still didn’t see the tree view? If not, then this behavior is expected (though I’d obviously love to hear feedback 😁).

Regarding the comment about trying to record a tour: when you ran the “CodeTour: Record Tour” command, did you get a prompt for a title and then a “Tour is recording!” toast? Also, if you start recording and then open the Explorer tab, so you see the CodeTour tree view at the bottom?

I just want to confirm whether or not you’re having issues with recording, or if the “comment gutter” isn’t showing up.

**Comment by alpaix** [comment] 2020-05-20 01:58
Got it. For a first-time user the experience is a bit confusing. I needed to actually read the instructions (the part where it reads "if it's visible") in addition to watching the video to get started.

Then, when recording had started I got a prompt and clicked "Cancel" button to hide it. As a result the recording got cancelled.

In summary, it's not a bug. Rather a confusing experience for a first-timer like me :)

**Comment by lostintangent** [comment] 2020-05-20 02:31
Yeah I definitely have a lot of room for usability improvements, so I appreciate you providing this feedback! At a minimum, I agree that the “Cancel” button on the recording toast isn’t particularly useful, and probably leads to more confusion than it’s worth. Users can always delete tours from the CodeTour tree if they don’t want them any more, and so the “Cancel” button isn’t particularly valuable. So I’ll remove that button this evening 👍

Any other thoughts on how I could improve the first-time use?

**Comment by alpaix** [comment] 2020-05-20 04:24
Thank you for the prompt response. It works great once you grasp basic flows. Markdown support is terrific. I'll record a tour and run it by my colleagues as well.

* I'd expect to have the codetour tree in the explorer tab by default. And maybe add a header button to hide/unpin it.
* The prompt itself might still be helpful. Instead of a cancel button, having "ok/hide" and "don't show again" buttons would be more consistent.

**Comment by RandomFractals** [comment] 2020-05-20 11:48
hey @lostintangent what if you added an extension setting to show code tour tree view welcome page and in that view provide info to get started and create new code tour?

Then devs experienced code devs could disable code tour tree view welcome page display via extension setting if it clutters their workspace too much, but new devs just getting started with code tour will be able to create new tours.

That enhancement might also prompt devs to create code tours for their projects if the welcome to code tour tree view is displayed by default ;)

**Comment by lostintangent** [comment] 2020-05-25 19:29
@RandomFractals Yeah I think that could work 👍 

BTW, I'm going to close this as a duplicate of #41, which is already covering the onboarding experience. That way, we can consolidate the discussion into one place. Thanks!

**Closed by lostintangent** 2020-05-25 19:29 UTC
Labels: area: recording
