### ISSUE TITLE
Add Navigation Options

### ISSUE THREAD

**Issue by johnpapa** [vsls-contrib/codetour#28] opened 2020-03-13 14:31 UTC
I think to navigate I am supposed to either use the ouse/trackpad and click on steps in the tree OR focus on a step, click CMD ->.

But the latter doesnt work without having to re-focus on the next step. For example:

- open step 1 with the mouse
- click on step 1's visual interface
- click CMD ->
- now click on step 2's visual interface
- click CMD ->

Notice that we have to keep putting focus back on the step. It would be nice to allow full keyboard control to use CMD -> and CMD -< to go forward and backward without having to reset focus.

**Comment by lostintangent** [comment] 2020-03-13 22:05
This is essentially a duplicate of #9, since I need to focus the comment UI whenever it's displayed (either due to authoring or navigating). So once I fix that, it will address this as well.

**Closed by lostintangent** 2020-03-13 22:05 UTC
