### ISSUE TITLE
[bug] folder steps don't work properly when codetour panel is outside the file explorer tab

### ISSUE THREAD

**Issue by alvaromartmart** [vsls-contrib/codetour#65] opened 2020-05-07 10:46 UTC
Folder steps introduced in #40 are great!
However, when a tour runs into a folder step it doesn't properly focus on the folder if the CodeTour panel is not embedded on the file explorer tab (related to #44 )

Steps to reproduce:
- Create a tour with a folder step
- Drag the codetour from the file explorer tab to the toolbar
- Start the tour and go to the folder step

Expected behavior:
- The file explorer tab should gain focus, together with the specified folder

Current behavior:
- The file explorer tab momentarily gains focus, but inmediately later so does the codetour tab

**Comment by lostintangent** [comment] 2020-05-07 15:23
@alvaromartmart Yeah unfortunately this isn't currently possible, without me removing the logic that keeps the `CodeTour` tree in sync with the current tour step (which I added after a bunch of user feedback). Now that the `Explorer` tree is also important for selection, we now have two tree views that are equally as important, and need to be visible at the same time 😄 

This is actually why I've kept the `CodeTour` tree in the `Explorer` tab by default, so the two trees are always visible. The moment you move the `CodeTour` tree to another tab, this model breaks. So I wonder if this is actually a good argument for moving the `CodeTour` tree to the "panel" by default (the bottom section with the terminal, problems list, etc.), since that section could be visible at the same time as the `Explorer` tree. This is actually where I keep the `CodeTour` tree myself, but maybe it makes sense for it to be here for everyone, since it's effectively a "global" list like the `Problems` pane. Thoughts?

![image](https://user-images.githubusercontent.com/116461/81312599-a988b380-903b-11ea-8451-2bf9415387ae.png)

**Comment by lostintangent** [comment] 2020-05-07 16:16
@alvaromartmart What's your thoughts on moving the `CodeTour` tree to the bottom panel by default? Would that work for your workflow?

**Comment by alvaromartmart** [comment] 2020-05-08 08:16
@lostintangent I agree! I hadn't thought of moving it to the bottom panel... just tested it and I think it makes sense. Setting it as a default sounds like a good idea.

**Comment by lostintangent** [comment] 2020-05-11 04:00
OK cool, I’ll close this as a duplicate of #44 then, and I’ll use that issue to track changing the default location. Thanks!

**Closed by lostintangent** 2020-05-11 04:00 UTC
Labels: area: playback, bug
