### ISSUE TITLE
Allow recording code input

### ISSUE THREAD

**Issue by legomushroom** [vsls-contrib/codetour#4] opened 2020-03-08 04:05 UTC
The `Code Tour` allows recording comments in a sequence on a particular line.

`Feature request:` add another type of the tour step - "code input" where the author can record their code input as they code. The extension will then replay their input back to the users on those steps, creating richer interactive tutorials and hands-on user guides.

**Comment by lostintangent** [comment] 2020-06-28 21:35
I’d love to hear more from folks about what their use cases are for recording coding input. I have some ideas of how this could work, but I want to make sure it’s oriented in the intent of the tour.

**Comment by lostintangent** [comment] 2020-11-07 04:12
Closing this as a duplicate of #97.

**Closed by lostintangent** 2020-11-07 04:12 UTC
Labels: area: github, area: recording, enhancement
