### ISSUE TITLE
Add support for multi-root workspaces

### ISSUE THREAD

**Issue by cogoo** [vsls-contrib/codetour#13] opened 2020-03-08 22:39 UTC
Thank you so much for this plugin! Awesome idea.

Issue: 
When using VSCode workspaces, the path to the recorded file is incorrect.
When starting a recorded tour, I get the error:

> unable to resolve non-existing file

**Comment by lostintangent** [comment] 2020-03-08 22:50
Hey! Yeah, this is a known issue. The extension is currently 100% specific to there being a single workspace, which is an obvious flaw 😁 I’ll try to knock our workspace support this evening. Thanks for reporting this!

**Comment by yamgent** [comment] 2020-03-10 03:08
Hi, will this issue eventually allow a single tour to span across multiple workspace folders, or is this issue purely concerned with fixing the inability to create tours for workspace folders other than the first one?

**Comment by lostintangent** [comment] 2020-03-10 03:13
Both! I’m hoping to address this in the next couple of days.

**Comment by lostintangent** [comment] 2020-03-15 04:30
Closing this as a duplicate of #1.

**Closed by lostintangent** 2020-03-15 04:30 UTC
Labels: area: playback, area: recording, bug
