### ISSUE TITLE
Tour displacement when editing code

### ISSUE THREAD

**Issue by gsmile** [vsls-contrib/codetour#59] opened 2020-04-28 18:13 UTC
What happens to a tour step when code gets refactored? The durability of the tours beyond the short-term, could use some thinking. This has been an issue brought up in user research by customers.

**Comment by lostintangent** [comment] 2020-05-04 03:53
Closing this as a duplicate of #53, so that we can track all decay improvements in one place 👍

**Closed by lostintangent** 2020-05-04 03:53 UTC
Labels: area: playback, enhancement
