### ISSUE TITLE
Allow replaying code tours on GitHub

### ISSUE THREAD

**Issue by mathieudutour** [vsls-contrib/codetour#10] opened 2020-03-08 19:08 UTC
A lot of devs don’t use vs code, it would be amazing for them to be able to play the tours on the web, without needing to download vs code for that (I think it’s fair to require vs code to record a tour)

**Comment by lostintangent** [comment] 2020-03-08 19:20
With some help from @nat and team, I'd love to explore if we could build something like this directly into GitHub itself, without relying on a browser extension. I built this initial experience into VS Code, so that I could explore the idea/UX. However, I completely agree that it's value extends far beyond the editor, and GitHub is the perfect home 👍

**Comment by mathieudutour** [comment] 2020-03-08 19:24
That'd be amazing, I'd love to help explore that idea

**Comment by nat** [comment] 2020-03-08 19:32
If you have a mockup of how it could work in GitHub, that might help kick off the conversation. Thinking about how to avoid metadata bit rot would also be good.

**Comment by lostintangent** [comment] 2020-03-08 19:37
@nat I'll be thinking through the decay problem this week, and I'll throw together some initial mockups as well!

**Comment by rand** [comment] 2020-03-09 15:15
@lostintangent would associating the code tour with a concrete tagged release help with the decay problem (and add a more static link to the resource)?

**Comment by lostintangent** [comment] 2020-03-15 04:29
@rand I think so! I just made an update to the recorder, which asks you which git ref you'd like to associate the tour with. It displays all available tags, and lets you select either a one of those tags, the current branch, the current commit, or "none" (which lets the tour apply to all versions).

![image](https://user-images.githubusercontent.com/116461/76692462-3f8ff700-6614-11ea-88a1-6fbded8e8507.png)

When you replay a tour that's for an older ref than `HEAD`, then it will navigate you through a read-only version of the tour, using the version of the associated files from the recorded ref. That way, the tour is always accurate.

You can also update the Git ref association at any time by right-clicking a tour in the `CodeTour` tree and selecting `Change Git Ref`. That will display the same pick-list as above, but will let you "fast-forward" the tour to future commits/tags/branches if it applies. I feel like there's more work that I can do here to make this experience smoother, but this seemed like a decent starting point to prevent "decay" of the tour.

**Comment by rand** [comment] 2020-03-16 14:18
@lostintangent that is awesome! i can't wait to get this integrated on the web client side, too.

**Comment by themmes** [comment] 2020-03-22 11:43
Spotted your project on HN this morning, cool stuff!

I was thinking to counter bitrot wouldnt it be convenient to actually place this in the code commenting. Much like `TODO`?

```
// CODETOUR: <#> "<Some title>" #L0-99 ...
```

Where you..
- assign `<#>` manually or leave it out and assign interactively using some CLI later
- can add a (or multiple) subset(s) of lines (code comments and actual code) to click/spacebar through as a CODETOUR

**Comment by lostintangent** [comment] 2020-03-22 14:58
@themmes Thanks for the suggestion! I’ve actually been considering adding support for this, as an alternate “tour definition provider”. That said, there are a few elements about this approach that have given me a little pause:

1. The comments would clutter the code for everyone that’s viewing it, as opposed to enriching the code for those that are taking the associated tour. This might not be a big deal, but in order to achieve long-term traction, I can’t help but feel like being unobtrusive has value. The “side car annotations” approach helps with this, and so it just comes down to the trade offs that teams are willing to make.

2. I want the tour to be able to span *all* file types, and I’m not sure if the comment-driven approach would naturally work in 100% of meaningful scenarios. For example, how would you define a step in a JSON file (since it doesn’t support comments)? Since the role that declarative code/metadata plays in codebases can be a huge source of confusion, I felt like we needed a solution that was fully agnostic to the grammar of any specific file. 

3. A codebase can define n-number of tours, and therefore, a single line of code could actually contribute to multiple different tours. Having a line annotated with two (or more) different tour descriptions could amplify amplify the potential for clutter. 

All that said, I definitely think the comment-driven approach has a lot of value, particularly for reducing bit rot. That said, I just wanted to share some concerns I have about it, and give some context about why I’ve initially chosen to go with the “side car file” + associating a tour with a commit/tag.

Let me file a separate issue to discuss this suggestion, so we can track progress on it separately from any GitHub integrations. Thanks!

**Comment by linonetwo** [comment] 2020-03-26 02:59
There used to be an online version that I really like: [partyparrot/codetours](https://github.com/partyparrot/codetours)

It is dead, but maybe it can be taken as a reference.

**Comment by lostintangent** [comment] 2020-03-26 03:53
@linonetwo Thanks! I had no idea there was a previous project called code tour as well 😁

Out of curiosity: what would you think about having a browser-hosted version of VS Code, that allowed taking a tour of any GitHub repo? That way there would be complete symmetry between the web and desktop experiences, but you had the ability to richly browse codebases in your browser too?

**Comment by linonetwo** [comment] 2020-03-26 07:56
Yes, back to the time I search for a solution like `partyparrot/codetours`, I was just looking for a way to share code via a link, it is like carbon.now.sh/ or GitHub gist, but can deliver more context and feels like a tutor.

As for a browser-hosted version of VSCode, I frequently use stackblitz to reproduce bugs when I raise an issue (for example, https://stackblitz.com/edit/react-three-fiberissues120 ). Its drawback is that it can't install extensions like this codetour extension.

Do you mean there will be an official browser-hosted version of VSCode that ships with full extension API?

**Comment by lostintangent** [comment] 2020-05-07 02:03
Now that it's officially announced, I can finally point at [this](https://github.com/features/codespaces) as being the potential solution here 😄 Since the editor-based experience is so immersive, it feels like simply providing that in a light-weight, hyper-linkable, browser-based solution would be an amazing step forward for helping people onboard to projects.

In fact, here's a screenshot of me taking a code of the CodeTour codebase, after simply opening up the repo in a Codespace from github.com/vsls-contrib/codetour. 

![image](https://user-images.githubusercontent.com/116461/81246128-a35aee80-8fcb-11ea-98d3-e8ef63dfa5f4.png)

// CC @nat

**Comment by lostintangent** [comment] 2020-09-11 19:43
I'm going to close this issue for now, since per my previous comment, I think Codespaces is the natural mechanism for enabling developers to replay a tour from GitHub. If we end up finding that there's strong value/demand in showing tours directly on github.com (as opposed to as part of the editor), we can track that discussion closer to the product team that would implement it 👍

**Closed by lostintangent** 2020-09-11 19:43 UTC
Labels: area: playback, enhancement

**Comment by qmenoret** [comment] 2021-01-19 08:42
Hello, just so you know we started implementing a Browser extension for Code Tours: https://github.com/doctolib/code-tours-github
Doesn't have all features yet, but we use it internally for people that don't use vscode :)
