### ISSUE TITLE
[bug] Error exporting tour - bad path

### ISSUE THREAD

**Issue by alvaromartmart** [vsls-contrib/codetour#47] opened 2020-04-02 10:37 UTC
Codetour does not work on my workspace. I can record a tour, but when I try to run it, clicking on the steps does nothing, it doesn't seem to "find" the files.

Then I tried to export the tour and I got this error, which suggests that the extension is not creating the right paths to the files referred to by the steps, am I right?

This is the error (just to be clear, the correct path is **/home/user/repos/my-repo/index.ts**)
```
Error running command codetour.exportTour: Unable to read file '/home/user/repos/my-repo/my-repo/index.ts' (EntryNotFound (FileSystemError): 
Error: ENOENT: no such file or directory, open '/home/user/repos/my-repo/my-repo/index.ts'). This is likely caused by the extension that contributes codetour.exportTour.
```

**Edit**: this occurs only while using a vscode workspace

**Comment by alvaromartmart** [comment] 2020-04-02 10:43
Actually I think this is the same issue as #1

**Comment by lostintangent** [comment] 2020-04-02 17:41
@alvaromartmart Yeah this is a duplicate of #1. CodeTour doesn't currently support workspaces, but I need to get this done ASAP. Apologies for the inconvenience here :/ In the meantime, I'll close this issue as a duplicate, and I'll track progress via #1. Thanks!

**Closed by lostintangent** 2020-04-02 17:41 UTC
